- name: Importaci贸n de claves del repo Kubic
  ansible.builtin.apt_key:
    url:  https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key
    keyring: /usr/share/keyrings/libcontainers-archive-keyring.gpg
    state: present

- name: Importaci贸n de claves del repo CRI-O
  ansible.builtin.apt_key:
    url:  https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/Release.key
    keyring: /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
    state: present


- name: Repositorio kubic
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04 /
    state: present

- name: Repositorio CRI-O
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04/ /
    state: present

- name: Instalaci贸n de CRI-O
  apt:
    pkg:
    - cri-o
    - cri-o-runc

- name: Reinicio de los daemon de Systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Activaci贸n de CRI-0 al inicio
  ansible.builtin.systemd:
    name: crio

- name: Inicio de CRI-0
  ansible.builtin.systemd:
    state: started
    name: crio