- name: Instalación de paquetes necesarios para los repositorios.
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - bash-completion

- name: Add kernel modules enabled at startup
  ansible.builtin.copy:
    src: ../files/modules
    dest: /etc/modules

- name: Enable overlay module
  ansible.builtin.command: modprobe overlay

- name: Enable br_netfilter module
  ansible.builtin.command: modprobe br_netfilter

- name: Adición de políticas
  ansible.builtin.copy:
    src: ../files/99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf